services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ing
    ports:
      - "8099:99"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database/postgresIng
    depends_on:
      - database
    volumes:
      - ./:/app   

  database:
    image: postgres:15
    container_name: postgresIng
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresIng
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro 

volumes:
  db_data:
